In [1]:
import numpy

In [3]:
vector = [1, 2, 3]

In [4]:
print(type(vector))

<class 'list'>


In [7]:
# convert a python list to numpy array
nvector = numpy.array(vector)

In [6]:
print(type(nvector))

<class 'numpy.ndarray'>


In [9]:
# return shape of numpy array
nvector.shape

(3,)

In [10]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [11]:
nmatrix = numpy.array(matrix)

In [12]:
nmatrix.shape

(3, 3)

In [13]:
j = 3

i = [5, 7, 9]

k = [
    [5, 7, 8],
    [1, 5, 3],
    [7, 4, 9]
]

# tensor: list of lists that each list contains a list
x = [
    [[1, 2, 3], [4, 5, 6], [7, 9, 10]],
    [[7, 8, 9], [10, 11, 12], [6, 4, 8]],
    [[5, 7, 9], [17, 31, 12], [16, 14, 12]]
]

In [12]:
narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [5]:
# change size of an numpy array
numpy.resize(narr, (4, 4))

# also you can use like below:
# narr.resize((3, 3), refcheck=False)
# narr

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [8]:
# create a numpy array that are fields are 1
matrix = numpy.ones((5, 4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# create a numpy array that are fields are 0
matrix = numpy.zeros((4, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# returns the diagonal elements of the array
numpy.diag(narr)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
# repeat each element in list  
numpy.repeat([1, 2, 3], 5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [22]:
m1 = numpy.ones((4, 5), dtype=int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
m2 = numpy.zeros((4, 5), dtype=int)
m2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
# function is used to stack arrays in a vertical sequence (row-wise)
numpy.vstack([m1, m2])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
# function is used to stack arrays in a horizontal sequence (column-wise)
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [7]:
# multiply lists with numpy array
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])

In [8]:
z = x * y
z

array([ 4, 10, 18])

In [9]:
# power
x ** 2

array([1, 4, 9])

In [10]:
# Internal multiplication
x.dot(y)

32

In [2]:
yarr = numpy.array([
    [1, 2, 3],
    [0, 0, 0],
    [0, 0, 0]
])

In [3]:
yarr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
# transpose
yarr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [24]:
# change type of an numpy array
yarr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [25]:
# calculates the sum of all elements in the array
yarr.sum()

6

In [26]:
# returns the minimum element in the array
yarr.min()

0

In [27]:
# returns the maximum element in the array
yarr.max()

3

In [28]:
# returns the index of the maximum value in the array
yarr.argmax()

2

In [29]:
# returns the index of the minimum value in the array
yarr.argmin()

3

In [5]:
# calculates the arithmetic mean of all elements in the array
# computes the average value of the elements contained in the array
yarr.mean()

0.6666666666666666

In [6]:
# calculates the standard deviation of the elements in the array
yarr.std()

1.0540925533894598

In [10]:
# is a function that creates an array containing evenly spaced values within a specified range. It is similar to Python's built-in range() function but returns an array instead of a list
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [12]:
mr[-6:14:2]

array([ 81, 121, 169])

In [13]:
mr[2]

4

In [14]:
mr[1:5]

array([ 1,  4,  9, 16])

In [15]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [9]:
warr = numpy.array(
    [
        [1, 2, 3],
        [0, 0, 0],
        [0, 0, 0]
    ]
)
warr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
warr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [19]:
warr[::2, -1]

array([3, 0])

In [20]:
warr[::2, -1:]

array([[3],
       [0]])

In [21]:
warr[::-1, 2:]

array([[0],
       [0],
       [3]])

In [25]:
warr[warr >= 0]

array([1, 2, 3, 0, 0, 0, 0, 0, 0])

In [26]:
warr[warr >= 2]

array([2, 3])

In [27]:
warr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [28]:
marr = warr[-1]
marr

array([0, 0, 0])

In [29]:
marr[:] = 1
marr

array([1, 1, 1])

In [31]:
marr[:2] = 2
marr

array([2, 2, 1])

In [32]:
warr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [33]:
# copy an array to another variable
marr = warr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [5]:
tarr = numpy.random.randint(0, 10, (4, 3))
tarr

array([[4, 4, 3],
       [8, 7, 0],
       [6, 7, 9],
       [6, 2, 1]])

In [6]:
tarr[3::3, 4:1:-2]

array([[1]])

In [7]:
for i in tarr:
    i = i ** 2
    print(i)

[16 16  9]
[64 49  0]
[36 49 81]
[36  4  1]


In [8]:
for i, j in enumerate(tarr):
    print(f"index(' {i} ') is: {j}")

index(' 0 ') is: [4 4 3]
index(' 1 ') is: [8 7 0]
index(' 2 ') is: [6 7 9]
index(' 3 ') is: [6 2 1]


In [10]:
list(zip(warr, tarr))

[(array([1, 2, 3]), array([4, 4, 3])),
 (array([0, 0, 0]), array([8, 7, 0])),
 (array([0, 0, 0]), array([6, 7, 9]))]

In [12]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]
arr = numpy.array((arr))
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
len(arr) // 2

4

In [16]:
p = [len(arr) // 2]
p

[4]

In [18]:
l = [x for x in arr if x < p]
l

[1, 2, 3]

In [19]:
r = [x for x in arr if x > p]
r

[5, 6, 7, 8]

In [20]:
m = [x for x in arr if x == p]
m

[4]

In [25]:
l + m + r

[1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array((arr))
    p = arr[len(arr) // 2]
    l = [x for x in arr if x < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [24]:
h = [3, 6, 4, 1, 3, 9, 5]
quicksort(h)

[1, 3, 3, 4, 5, 6, 9]